### ISSUE TITLE
Multiple logins to extension Component Library

### ISSUE THREAD

**Issue by Bosssaa** [moreblocksadmin/bugs#1]
**Describe the bug**
Every time I go from page to WP dashboard and then back to page I need to insert username and password.

**To Reproduce**
1. Create and go to 'Page'
2. Log into extension
3. Create any sections and few elements with extension and "Save"
4. Go to WP dashboard and create new page
5. Go into page and click on the extension
6. It will ask you to type in credentials

**Expected behavior**
I should be able to go out of pages and into pages without multiple log ins.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Additional context**

**Comment by deeperlook** [comment]
Experiencing the same issue in Chrome (114.0.5735.199) and Brave (v1.56.9) browsers on Windows 10.

**Comment by moreblocksadmin** [comment]
I noticed this, on the final release of moreblocks, there won't be logins for the extension. Needed it just for beta testing.
