### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by rubengarciajr** [moreblocksadmin/bugs#10]
I have an idea, what if when you log-in, you have the most popular layouts to create a page
Nav
Banner
Content
CTA
Content
Footer

instead of always loading the NAV - you can change this every month of based on popularity 

<img width="311" alt="Screenshot 2023-07-29 at 10 07 01 AM" src="https://github.com/moreblocksadmin/bugs/assets/24701396/512bb9f1-5cef-4304-888a-52608bbaa94c">

**Comment by moreblocksadmin** [comment]
Implemented a popular filter, will add a few more later. 

![pupolar 2](https://github.com/moreblocksadmin/bugs/assets/138633247/c886dd5b-0927-4c56-8722-576c566edc81)
