### ISSUE TITLE
Landing Page 10

### ISSUE THREAD

**Issue by rubengarciajr** [moreblocksadmin/bugs#13]
Fresh install of wordpress - ZERO global styling edit - copy + paste Landing page 10 

GRID imported with Grid layout Row 3 - changed to 2 and seemed to fix the layout

import row setting
![Screenshot 2023-09-09 at 4 05 54 PM](https://github.com/moreblocksadmin/bugs/assets/24701396/84b026c9-3523-4f85-a4ab-b0ab07fe7037)

changed grid row setting 
![Screenshot 2023-09-09 at 4 06 01 PM](https://github.com/moreblocksadmin/bugs/assets/24701396/815abc41-7490-42d7-addd-b084a114c129)

**Comment by moreblocksadmin** [comment]
Issued was with selector not included in the copied template. It has been fixed now. Thanks
