### ISSUE TITLE
Image Aspect Ration + Object Fit 

### ISSUE THREAD

**Issue by rubengarciajr** [moreblocksadmin/bugs#2]
To help the user experience with your intended design 

<img width="1332" alt="Screenshot 2023-07-15 at 4 23 37 PM" src="https://github.com/moreblocksadmin/bugs/assets/24701396/5b208a96-93b9-4e96-8586-1c161923fabd">

Might be best to set the aspect ratio and object fit 

<img width="282" alt="Screenshot 2023-07-15 at 4 21 37 PM" src="https://github.com/moreblocksadmin/bugs/assets/24701396/2c6d2090-738f-4ac4-9814-29e330a0bc3e">

this will allow your design to stay 100% as intended 

<img width="1225" alt="Screenshot 2023-07-15 at 4 21 30 PM" src="https://github.com/moreblocksadmin/bugs/assets/24701396/2984d833-6dff-41fb-9ee6-b1683a03cf84">

Just an idea

**Comment by moreblocksadmin** [comment]
Did not want to set in stone some of the designs, to make them flexible, but i think that might affect it more than do good. I might have to set the width for some of the images.
