### ISSUE TITLE
Search doesn't work technically 

### ISSUE THREAD

**Issue by rubengarciajr** [moreblocksadmin/bugs#3]
You can search for items "heros",  it doesn't allow you to copy and paste to the builder and you can't reset the EXT . you have to close the brower and restart 

<img width="370" alt="Screenshot 2023-07-15 at 5 03 31 PM" src="https://github.com/moreblocksadmin/bugs/assets/24701396/3325782d-8073-49d9-92d0-fd4139f39028">

**Comment by moreblocksadmin** [comment]
@rubengarciajr  For the search, it should work on the extension when moreblocks is out beta nd released to the public. 
![search](https://github.com/moreblocksadmin/bugs/assets/138633247/4a4058b1-b7d4-4dcc-b154-7535a5b45fd0)
