### ISSUE TITLE
Filter Options

### ISSUE THREAD

**Issue by rubengarciajr** [moreblocksadmin/bugs#4]
Can we have this open my default to show ALL cateogries, we have to do two - three clicks to get back there 

<img width="380" alt="Screenshot 2023-07-15 at 4 30 28 PM" src="https://github.com/moreblocksadmin/bugs/assets/24701396/a5a5f83a-c09f-4565-9482-dae18c59d028">

**Comment by moreblocksadmin** [comment]
Yes, i think that should be a wise move. I have implemented that on main site.
