### ISSUE TITLE
Coming Soon 8 - Outline Effect - Overlapping 

### ISSUE THREAD

**Issue by deeperlook** [moreblocksadmin/bugs#5]
**Describe the bug**
In the Comming Soon 8 template, the outline effected used on the words 'Coming Soon' overlaps the shapes of the lettering.

**To Reproduce**
1. Copy Coming Soon 8 template into a Breakdance page.
2. The error is visible both in the preview window and on the live version.

**Expected behavior**
The stroke effect is expected to be around the outline of the words.

**Screenshots**
A 
![outline effect overlapping](https://github.com/moreblocksadmin/bugs/assets/32532621/725c2fb9-c0c6-44d7-a530-adf8151d35f6)
screenshot has been attached to show the issue.

**Comment by moreblocksadmin** [comment]
Can you change your fonts and see if the same issue persist, because I couldn't replica it on my side.

**Comment by moreblocksadmin** [comment]
Text issue depends on the form being used, so I am closing this one.
