### ISSUE TITLE
Media Library buttons unable to be selected with Extension Open

### ISSUE THREAD

**Issue by GalwayCal** [moreblocksadmin/bugs#6]
When editing a page in breakdance with the extension open you are unable to add images from the media library without closing the extension.

Steps to reproduce the behaviour:
1. Open page to be edited.
2. Open extension and copy block with images.
3. Click replace to change image.
4. Upload or Select image from Media Library.
5. The Image Meta and "Choose" button are hidden behind the extension fly-out.
 
**Expected behaviour**
Should be able to insert media without have to close the extension as currently need to log back in on reopening.

**Screenshots**
![Screenshot 2023-07-24 at 9 21 47 am](https://github.com/moreblocksadmin/bugs/assets/52806314/e95f9bfb-5c7d-4b74-8fcd-888a4807a8cf)

 - OS: Mac OS 13.2.1 
 - Browser Chrome Version 114.0.5735.198

**Comment by moreblocksadmin** [comment]
I've made an update so that the extension library is hidden when you click either the "choose" button or the surrounding div. This resolves the problem of the library remaining visible when selecting media.
