### ISSUE TITLE
Add a Filter Update button

### ISSUE THREAD

**Issue by deeperlook** [moreblocksadmin/bugs#7]
**Describe the bug**
After selecting a filter, the templates automatically appear. This means any options already selected could appear above the newly filtered options causing you to either go back and unselect them one update at a time, or scroll through each page of results until you reach the desired templates.

**Expected behavior**
Rather than automatically updating, it seems more useful to have an update button allowing you to select/unselect multiple filtering options in one go. 

**Desktop (please complete the following information):**
 - Win 10
 - Chrome

**Comment by moreblocksadmin** [comment]
I update will be released to fix that as I have demonstrated in the video below.

https://www.loom.com/share/71ba59aee3764e0791b9551615b1dbf0?sid=6e798428-d8cd-4e22-903b-59b08949a6f8

**Comment by moreblocksadmin** [comment]
I update will be released to fix that as I have demonstrated in the video below.

https://www.loom.com/share/71ba59aee3764e0791b9551615b1dbf0?sid=6e798428-d8cd-4e22-903b-59b08949a6f8
