### ISSUE TITLE
Infinite scrolling of blocks

### ISSUE THREAD

**Issue by deeperlook** [moreblocksadmin/bugs#8]
**Describe the bug**
It can become time-consuming having to search through pages for blocks, especially if you have a filtering option with 50+ blocks or a 3+ components ticked.

**Expected behavior**
Removing pagination and implementing a lazy load infinite scroll instead would be great.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome

**Comment by Buda9** [comment]
I agree. And a quick search would also be nice idea, so we can go faster to e.g. "header 45"

**Comment by moreblocksadmin** [comment]
Below video I have demonstrated the new filtering system and a load more button. This is one the main site, so you wont see it on the beta site yet. 

https://www.loom.com/share/6b029017b3fc479faaba83953794f578?sid=3d8e2331-3762-4520-8773-09c74dbe0f45

**Comment by Buda9** [comment]
Great! I love it!
