### ISSUE TITLE
Few issues I noticed during beta testing

### ISSUE THREAD

**Issue by Buda9** [moreblocksadmin/bugs#9]
![Screenshot_1](https://github.com/moreblocksadmin/bugs/assets/1422662/d6f6e09d-5f9b-49b4-9100-4b5852e977ac)
![Screenshot_2](https://github.com/moreblocksadmin/bugs/assets/1422662/fa98be25-aba2-40ef-b75c-576091dd4bae)
![Screenshot_3](https://github.com/moreblocksadmin/bugs/assets/1422662/5fb7f0f8-cbe6-491b-8e6e-6415879849af)
![Screenshot_4](https://github.com/moreblocksadmin/bugs/assets/1422662/7f4aafe8-244b-4bbc-9dc2-e7c804e95592)
![Screenshot_5](https://github.com/moreblocksadmin/bugs/assets/1422662/3b00d96b-9a27-4467-bf1a-e6796aedea43)
![Screenshot_6](https://github.com/moreblocksadmin/bugs/assets/1422662/1daa8f9a-6a5d-443d-bac8-f14252fe7a9b)

**Comment by moreblocksadmin** [comment]
I have initiated updates for all the issues listed above. Thanks

teams 13 - fixed
hero 19 - fixed
Gallery 16 - fixed
Gallery 10 - fixed
Navbar 19 - fixed
navbar 12 - fixed
